### ISSUE TITLE
dev-libs/gtkd:3 does not yet install pkg-config files gtkd-3.pc and vted-3.pc

### ISSUE THREAD

**Issue by hartwork** [gentoo/dlang#53] opened 2017-03-28 22:10 UTC
Hi!

I was trying to package [Tilix](https://github.com/gnunn1/tilix) but I'm having a hard time because it needs pkg-config files  `gtkd-3.pc` and `vted-3.pc` of `dev-libs/gtkd:3` to compile:
```
[..]
checking for GTKD... no
checking for GTKD... no
configure: error: Package requirements (gtkd-3 >= 3.3.0 vted-3 >= 3.3.0) were not met:

No package 'gtkd-3' found
No package 'vted-3' found
[..]
```
The gtkd Makefile comes with a `install-headers` target that may work:
```
# fgrep .pc /var/tmp/portage/dev-libs/gtkd-3.3.0/work/gtkd-3.3.0/GNUmakefile | head -n 20
pkgconfig-gtkd:      gtkd-$(MAJOR).pc
pkgconfig-gtkdgl:    gtkdgl-$(MAJOR).pc
pkgconfig-sv:        gtkdsv-$(MAJOR).pc
pkgconfig-gstreamer: gstreamerd-$(MAJOR).pc
pkgconfig-vte:       vted-$(MAJOR).pc
gtkd-$(MAJOR).pc:
gtkdgl-$(MAJOR).pc:
gtkdsv-$(MAJOR).pc:
gstreamerd-$(MAJOR).pc:
vted-$(MAJOR).pc:
install-headers-gtkd: gtkd-$(MAJOR).pc
        install -m 644 gtkd-$(MAJOR).pc $(DESTDIR)$(datadir)/pkgconfig
install-headers-gtkdgl: gtkdgl-$(MAJOR).pc install-headers-gtkd
        install -m 644 gtkdgl-$(MAJOR).pc $(DESTDIR)$(datadir)/pkgconfig
install-headers-gtkdsv: gtkdsv-$(MAJOR).pc install-headers-gtkd
        install -m 644 gtkdsv-$(MAJOR).pc $(DESTDIR)$(datadir)/pkgconfig
install-headers-gstreamer: gstreamerd-$(MAJOR).pc install-headers-gtkd
        install -m 644 gstreamerd-$(MAJOR).pc $(DESTDIR)$(datadir)/pkgconfig
install-headers-vte: vted-$(MAJOR).pc install-headers-gtkd
        install -m 644 vted-$(MAJOR).pc $(DESTDIR)$(datadir)/pkgconfig
```
Thanks for you help!

Best, Sebastian

**Comment by mleise** [comment] 2017-04-04 23:32
I know about this since starting the overlay. The idea is that pkg-config provides the set of flags for gcc to link against a library on a specific system. But gtkd can be installed for dmd, gdc, ldc2 and built by a variety of compiler versions with potentially incompatible ABIs. I.e. I can't guarantee that gtkd built for dmd-2.070 will work when Tilix is compiled with dmd-2.072.
Similarly gtkd built with gdc wont work in Tilix built with dmd, which shows through in its configure script:
https://github.com/gnunn1/tilix/blob/master/configure.ac#L41
You can see that the author worked around the latter problem by giving the *.pc files compiler specific suffixes (-dmd, -gdc, -ldc). But since I also distinguish between compiler _versions_ that is not enough.

Someone once proposed to drop the installation of libraries per compiler version. That will likely cause frequent linker or runtime errors when a new compiler is used to link a program and a library compiled with a previous version due to ABI changes. C++ is much more stable in that regard. In the years I've been using Gentoo I remember only one case of ABI breakage that had to be fixed by manually recompiling libraries with a new gcc version.

**Comment by hartwork** [comment] 2017-04-05 17:54
Hi! I see, that sounds tricky.

How about an eclass auto-spltting a .pc file at /usr/lib*/pkgconfig/*.pc into files for all compilers and versions? Would that work? How would they differ and is manual post-propressing needed?

For a workaround, I would need to either patch-replace the call to PKG_CHECK_MODULES or put some fake pkg-config returning flags as needed upfront in PATH in the ebuild? Is there a common workaround you would suggest?

**Comment by mleise** [comment] 2017-04-06 23:42
I just modified the gtkd-3.5.1 ebuild to install some custom pkgconfig files that omit the library path part, one for each compiler brand. It seems like Tilix' configure script does not work as intended. It does not pick up the suffixed *.pc files, so that needs to be fixed first.
The compiler used for Tilix must be in the dependency on gtkd. E.g.: >=dev-libs/gtkd-3.5.0:3[ldc2-1_0]. I have no code ready available for you since at the moment there is no package depending on gtkd in the overlay.

**Comment by hartwork** [comment] 2017-04-09 14:47
Thanks for the `.pc` files! Do I need to do anything more to get `vted*.pc` files as well?
Right now I get:
```
# qlist dev-libs/gtkd | fgrep .pc
/usr/share/pkgconfig/gtkd-3-dmd.pc
/usr/share/pkgconfig/gtkd-3-gdc.pc
/usr/share/pkgconfig/gtkd-3-ldc.pc
/usr/share/pkgconfig/gtkdgl-3-dmd.pc
/usr/share/pkgconfig/gtkdgl-3-gdc.pc
/usr/share/pkgconfig/gtkdgl-3-ldc.pc
```
Best, Sebastian

**Comment by mleise** [comment] 2017-04-11 18:34
If Tilix needs vte bindings, it needs to depend on gtkd with "vte" USE flag. That should be enough to install the `vte*.pc` files.
```
equery f gtkd:3 | grep .pc$
/usr/share/pkgconfig/gstreamerd-3-dmd.pc
/usr/share/pkgconfig/gstreamerd-3-gdc.pc
/usr/share/pkgconfig/gstreamerd-3-ldc.pc
/usr/share/pkgconfig/gtkd-3-dmd.pc
/usr/share/pkgconfig/gtkd-3-gdc.pc
/usr/share/pkgconfig/gtkd-3-ldc.pc
/usr/share/pkgconfig/gtkdgl-3-dmd.pc
/usr/share/pkgconfig/gtkdgl-3-gdc.pc
/usr/share/pkgconfig/gtkdgl-3-ldc.pc
/usr/share/pkgconfig/gtkdsv-3-dmd.pc
/usr/share/pkgconfig/gtkdsv-3-gdc.pc
/usr/share/pkgconfig/gtkdsv-3-ldc.pc
/usr/share/pkgconfig/peasd-3-dmd.pc
/usr/share/pkgconfig/peasd-3-gdc.pc
/usr/share/pkgconfig/peasd-3-ldc.pc
/usr/share/pkgconfig/vted-3-dmd.pc
/usr/share/pkgconfig/vted-3-gdc.pc
/usr/share/pkgconfig/vted-3-ldc.pc
```

**Comment by hartwork** [comment] 2017-04-12 10:34
I missing the `vte` use flag, sorry.

Now that I tred again I notice that the `Requires: ` lines are missing `-${compiler}` prefixes which makes `pkg-config --exists vted-3-dmd` fail. Also the '-L' part in `Libs:` looks like a leftover:
```
# cat /usr/share/pkgconfig/vted-3-dmd.pc 
Name: VteD
Description: A D binding and OO wrapper for Vte.
Version: 3.5.1
Libs: -L-lgtkd-3
Requires: gtkd-3
```

When fixing all that manually I run into "safe function ... cannot call system function ..." compile errors. Sigh :)

**Comment by mleise** [comment] 2017-04-12 14:35
Ah right, that needs to be changed. The `@safe` maybe a problem with a specific version of Dlang or with a specific compiler.

**Comment by mleise** [comment] 2017-04-14 02:04
Tilix seems to require at least dmd 2.070. I removed the pkgconfig files again, but added an ebuild for Tilix that passes some flags to the build script that circumvent pkgconfig alltogether when looking for GtkD. I've tested it with dmd 2.070 and ldc2 1.1. Custom compiler flags are still ignored and man pages for all available languages are always installed, and control characters in the terminal are not interpreted as expected, e.g. backspace moves the caret right. Other than that, it works.

**Comment by hartwork** [comment] 2017-04-23 17:23
Thanks for the Tilix ebuild! Control characters seem to work fine for me.

**Comment by mleise** [comment] 2017-04-29 03:04
The control character issue was my fault for installing ncurses with "minimal" USE flag. So nothing to worry about. I added the default enabled "crypt" USE flag to Tilix though, because it kept warning me that my vte installation was lacking GNUTLS encryption support (enabled via "crypt").
I'm closing this issue for the time being, since Tilix is in a usable state now on Gentoo. You might still want to do the ebuild maintenance, because I don't use Tilix myself.

**Closed by mleise** 2017-04-29 03:04 UTC
