### ISSUE TITLE
Fail compiling DMD 2.069.1 using 2.067

### ISSUE THREAD

**Issue by AndreaOrru** [gentoo/dlang#27] opened 2015-12-15 12:07 UTC
I'm getting this error while trying to compile the last version of DMD on my Funtoo Stable (pure64) machine:

<pre><code> * Package:    dev-lang/dmd-2.069.1
 * Repository: dlang
 * USE:        abi_x86_64 amd64 dmd-2_067 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking dmd.2.069.1.zip to /var/tmp/portage/dev-lang/dmd-2.069.1/work
>>> Source unpacked in /var/tmp/portage/dev-lang/dmd-2.069.1/work
>>> Preparing source in /var/tmp/portage/dev-lang/dmd-2.069.1/work/dmd2 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-lang/dmd-2.069.1/work/dmd2 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-lang/dmd-2.069.1/work/dmd2 ...
 * Building dmd...
make -j1 -C dmd/src -f posix.mak TARGET_CPU=X86 HOST_DMD=/opt/dmd-2.067/bin/dmd RELEASE=1 
make: Entering directory '/var/tmp/portage/dev-lang/dmd-2.069.1/work/dmd2/dmd/src'
CC=g++ /opt/dmd-2.067/bin/dmd idgen.d
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lphobos2
collect2: error: ld returned 1 exit status
--- errorlevel 1
posix.mak:350: recipe for target 'idgen' failed
make: *** [idgen] Error 1
make: Leaving directory '/var/tmp/portage/dev-lang/dmd-2.069.1/work/dmd2/dmd/src'
 * ERROR: dev-lang/dmd-2.069.1::dlang failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/dmd-2.069.1::dlang'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/dmd-2.069.1::dlang'`.
 * The complete build log is located at '/var/tmp/portage/dev-lang/dmd-2.069.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-lang/dmd-2.069.1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-lang/dmd-2.069.1/work/dmd2'
 * S: '/var/tmp/portage/dev-lang/dmd-2.069.1/work/dmd2'
</code></pre>

The problem seems to be in my dmd.conf:

<pre><code>[Environment]
DFLAGS=-I/opt/dmd-2.067/import -L--export-dynamic -defaultlib=phobos2 -L-L/opt/dmd-2.067/lib -L-rpath -L/opt/dmd-2.067/lib
</code></pre>

This is wrong as my libraries are installed in /opt/dmd-2.067/lib64. If I change dmd.conf manually, it works.

**Comment by mleise** [comment] 2015-12-25 00:29
I currently cannot work on fixing this. But could you tell me if it makes more sense to change the installation path to /opt/lib instead if this is your standard directory name?

**Comment by AndreaOrru** [comment] 2015-12-26 23:01
I guess the best thing is just to link lib to lib64, the way it's done on /usr/*.

**Comment by mleise** [comment] 2016-02-01 16:30
Just to be sure: Even on pure amd64 "/usr/lib" is not a directory but a symlink to "/usr/lib64"? I'll add those symlinks then to use the well trotted path.

**Comment by Dr-Terrible** [comment] 2016-03-04 14:53
I can reproduce the issue on `no-multilib` profiles:

```
>>> Emerging (1 of 1) dev-lang/dmd-2.070.0-r1::dlang
 * dmd.2.070.0.zip SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                          [ ok ]
>>> Unpacking source...
>>> Unpacking dmd.2.070.0.zip to /var/tmp/portage/dev-lang/dmd-2.070.0-r1/work
>>> Source unpacked in /var/tmp/portage/dev-lang/dmd-2.070.0-r1/work
>>> Preparing source in /var/tmp/portage/dev-lang/dmd-2.070.0-r1/work/dmd2 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-lang/dmd-2.070.0-r1/work/dmd2 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-lang/dmd-2.070.0-r1/work/dmd2 ...
 * Building dmd...
make -j1 -C dmd/src -f posix.mak TARGET_CPU=X86 HOST_DMD=/opt/dmd-2.067/bin/dmd RELEASE=1 
make: Entering directory '/var/tmp/portage/dev-lang/dmd-2.070.0-r1/work/dmd2/dmd/src'
CC=g++ /opt/dmd-2.067/bin/dmd idgen.d
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: error: cannot find -lphobos2
idgen.o:idgen.d:_D25TypeInfo_S5idgen8Msgtable6__initZ: error: undefined reference to '_D15TypeInfo_Struct6__vtblZ'
idgen.o:idgen.d:function _D5idgen7__arrayZ: error: undefined reference to '_d_arraybounds'
idgen.o:idgen.d:function _D6object7__arrayZ: error: undefined reference to '_d_arraybounds'
idgen.o:idgen.d:function _D6object8__assertFiZv: error: undefined reference to '_d_assert'
idgen.o:idgen.d:function _D6object15__unittest_failFiZv: error: undefined reference to '_d_unittest'
idgen.o:idgen.d:function _D4core4stdc6stdint7__arrayZ: error: undefined reference to '_d_arraybounds'
idgen.o:idgen.d:function _D4core4stdc6stdint8__assertFiZv: error: undefined reference to '_d_assert'
idgen.o:idgen.d:function _D4core4stdc6stdint15__unittest_failFiZv: error: undefined reference to '_d_unittest'
idgen.o:idgen.d:function main: error: undefined reference to '_d_run_main'
idgen.o:idgen.d:_D11TypeInfo_Pv6__initZ: error: undefined reference to '_D16TypeInfo_Pointer6__vtblZ'
idgen.o:idgen.d:_D11TypeInfo_Pv6__initZ: error: undefined reference to '_D10TypeInfo_v6__initZ'
idgen.o(.text.d_dso_init+0x28): error: undefined reference to '_d_dso_registry'
collect2: error: ld returned 1 exit status
--- errorlevel 1
posix.mak:367: recipe for target 'idgen' failed
make: *** [idgen] Error 1
make: Leaving directory '/var/tmp/portage/dev-lang/dmd-2.070.0-r1/work/dmd2/dmd/src'
```

> Just to be sure: Even on pure amd64 "/usr/lib" is not a directory but a symlink to "/usr/lib64"?

Yes, on a pure x86_64 profile (no-multilib), there isn't a directory named /usr/lib, but a symbolic link pointing to /usr/lib64:

```sh
(from a freshly installed Gentoo vm)
# ls -la /usr/ | grep lib64
lrwxrwxrwx   1 root  root         5 May  4 14:02 lib -> lib64
drwxr-xr-x 178 root  root    143360 Mar  4 14:34 lib64
```

> I'll add those symlinks then to use the well trotted path

It's not a good solution, IMHO. On pure x86_32,profiles, phobos2 is expected to be installed in `/opt/dmd-2.067/lib32` to work properly (if I recall correctly Mars' documentation), not in `/opt/dmd-2.067/lib`. The ebuild should adjust the paths according to the running arch without resolving to any symbolic links.

**Comment by mleise** [comment] 2016-03-10 14:19
Phobos' installation path is actually system dependent. On Debian you will find it in /usr/lib/{i386-linux-gnu,x86_64-linux-gnu} for example and it is possible that we move the *.so to the default system directory, too since it is versioned. What documentation about path requirements are you referring to?

**Comment by mleise** [comment] 2016-04-03 05:28
Could you try dmd-2.070.0 from the above mentioned fork ? First install it using an existing compiler and then compile it with itself to see if the new libraries are picked up.
The ebuild changes the dmd.conf the way you did on amd64, but I also tried to fix libraries for x86.

**Comment by mleise** [comment] 2017-04-04 15:27
Compilation works in an amd64 VirtualBox environment, so I'm closing this now.

**Closed by mleise** 2017-04-04 15:27 UTC
